In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
### Задание 1
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

In [3]:
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

In [4]:
### Задание 2
A1 = np.array([[1, 2, -1], 
                        [3, -4, 0], 
                        [8, -5, 2], 
                        [2, 0, -5],
                        [11, 4, -7]])

B1 = np.array([1, 7, 12, 7, 15])


In [5]:
np.linalg.lstsq(A1, B1, rcond=None)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [6]:
### Задание 3
A3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B3 = np.array ([12, 2, 1])
print(np.linalg.solve(A3, B3))
print(np.linalg.lstsq(A3, B3, rcond=None))
np.linalg.matrix_rank(A3, 0.0001)


[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]
(array([-7.69444444, -0.61111111,  6.47222222]), array([], dtype=float64), 2, array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))


2

In [7]:
import scipy.linalg
### Задание 4
### Вычислите LU-разложение матрицы:
A4 = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A4)



In [8]:
### Задание 5
###Найдите нормальное псевдорешение недоопределенной системы:
A5 = np.array([[1, 2, -1], [8, -5, 2]])
B5 = np.array([1, 12])
np.linalg.lstsq(A5, B5)

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))